# Generated by Django 5.2.5 on 2025-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.TextField(default="Unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="mobile_no",
            field=models.CharField(default="0000000000", max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
